Add ssr
deysan/dynamic-table pull request #2
Opened 2022-09-08 07:30 UTC by deysan

2022-09-08 07:47 UTC, max-mykhailenko requested changes

2022-09-08 07:47 UTC, max-mykhailenko commented on package.json
> +    "express": "^4.18.1",
без експресу

2022-09-08 07:47 UTC, max-mykhailenko commented on server.js
> +import { createServer as createViteServer } from 'vite';
без 'vite'

2022-09-08 07:47 UTC, max-mykhailenko commented on src/entry-server.tsx
> +export const render = () => {
по виклику сюди передається ще url, але тут поки нічого не приймається

2022-09-12 07:57 UTC, max-mykhailenko requested changes

2022-09-12 07:57 UTC, max-mykhailenko commented on server/table.ts
> +  for (let i = 0; i < inputData.m; i++) {
попробуй через Array.from({ length: M }, ()=> {})

2022-09-12 07:57 UTC, max-mykhailenko commented on server/validator.ts
> +const isNumeric = (num: any) =>
не any, а unknown

2022-09-12 07:57 UTC, max-mykhailenko commented on src/App.tsx
> +const App: React.FC<AppProps> = ({ data }) => {
React.FC не використовуй, краще просто через function оголошуй компоненти

2022-09-12 07:57 UTC, max-mykhailenko commented on src/App.tsx
> +const App: React.FC<AppProps> = ({ data }) => {
в чеклисті є пояснення чому

2022-09-12 07:57 UTC, max-mykhailenko commented on src/components/InputData.tsx
>    const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
а що зараз робить ця функція?

2022-09-12 07:57 UTC, max-mykhailenko commented on src/hooks/useData.tsx
>    const refreshTable = () => {
чому закоментував?

2022-09-12 07:57 UTC, max-mykhailenko commented on src/main.tsx
> +// @ts-ignore: Unreachable code error
треба просто затипізувати window

2022-09-14 07:57 UTC, deysan commented on src/hooks/useData.tsx
>    const refreshTable = () => {
Зайве

2022-09-14 07:58 UTC, deysan commented on src/components/InputData.tsx
>    const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
Видалив, зараз нічого не робіть

2022-09-14 07:59 UTC, deysan commented on src/main.tsx
> +// @ts-ignore: Unreachable code error
Зробив

2022-09-14 07:59 UTC, deysan commented on server/validator.ts
> +const isNumeric = (num: any) =>
Виправив

2022-09-14 07:59 UTC, deysan commented on src/App.tsx
> +const App: React.FC<AppProps> = ({ data }) => {
Замінив

2022-09-14 08:00 UTC, deysan commented on server/table.ts
> +  for (let i = 0; i < inputData.m; i++) {
Спробував, працює добре

2022-09-14 08:00 UTC, deysan commented
Доробив тестове за коментарями, видалив зайві частини коду (ті які були закоментовані, та ті що не використовувалися), типізував `window`, а також виправив тип де було `any` на `unknown`. Переписав створення таблиці через `Array.from`. І всюди замінив компоненти через `function`

2022-09-14 08:19 UTC, max-mykhailenko commented on server/validator.ts
> +  !isNaN(num as number);
as number дивна конструкція

2022-09-14 08:19 UTC, max-mykhailenko commented on src/components/InputData.tsx
> +    setTimeout(() => {
всі таймаути треба очищати коли списуєш їх в ефект. Тобто повертати функцію, яка очищає таймаут

2022-09-14 13:30 UTC, max-mykhailenko requested changes

2022-09-14 13:30 UTC, max-mykhailenko commented on src/components/Table.tsx
> +    setTimeout(() => {
треба очищати таймаути

2022-09-14 13:30 UTC, max-mykhailenko commented on src/main.tsx
> +  document.getElementById('root') as HTMLElement,
as HTMLElement його і правда може не бути

2022-09-15 06:12 UTC, deysan commented on src/components/InputData.tsx
> +    setTimeout(() => {
Додав clearTimeout

2022-09-15 06:12 UTC, deysan commented on src/components/Table.tsx
> +    setTimeout(() => {
Додав clearTimeout

2022-09-15 06:14 UTC, deysan commented
Додав очищення для всіх таймерів `clearTimeout()`

2022-09-15 10:00 UTC, max-mykhailenko approved these changes

2022-09-15 10:06 UTC, merged